### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by vicenrico** [albertus82/jface-utils#1]
Hello, I would like to use yout jface library for my program's preferences. I hace spanish properties file, but I don't know how to use it. Could you help me? Thanks in advance

**Comment by albertus82** [comment]
Hello, please put your **`jfacemessages_es.properties`** resource file in a  **`it.albertus.jface`** package into your application, then call **`JFaceMessages.setLanguage(String)`** to set the language you prefer. Please let me know if you solved the problem. Thanks.

**Comment by vicenrico** [comment]
It worked. Thank you very much.
