### ISSUE TITLE
Spanish translation & Restart required option

### ISSUE THREAD

**Issue by vicenrico** [albertus82/jface-utils#2]
Hi, again. Could you explain how the restartrequired option works?. I mean, it's only to show a message or can the app restart itself?

Sorry for posting the question in the issues tab, but I haven't found an email where I can do it.

By the way, I think you should contact the nebula project team, because your code is very good and I think you could join them.  I'm using your preferences jar in my program and it's awesome

**Comment by albertus82** [comment]
Hi @vicenrico, no problem, these issues can help other users having similar questions.

The `restartRequired` property (which you will probably map to the `IPreference.isRestartRequired()` method) is simply a flag that allows the [`Preferences`](https://github.com/Albertus82/JFaceUtils/blob/master/src/main/java/io/github/albertus82/jface/preference/Preferences.java) object to set its own `restartRequired` field to `true` when the user changes one or more options that are flagged in that way. So, when the user closes the preferences dialog, you can read that field (`Preferences.isRestartRequired()` method) and, in case, warn the user or take any other action.

Please see how the [`Preferences.java`](https://github.com/Albertus82/JFaceUtils/blob/master/src/main/java/io/github/albertus82/jface/preference/Preferences.java) class works, and look at this code for a real-world use case: [`PreferencesListener.java`](/Albertus82/EarthquakeBulletin/blob/master/src/main/java/io/github/albertus82/eqbulletin/gui/listener/PreferencesListener.java).

I'm sorry for the lack of documentation, I work on this project in my spare time, but I hope I can improve it in the near future. If you have other questions or issues, don't hesitate to write here again.

**Comment by vicenrico** [comment]
Thanks for the info. By the way, I would like to give you the spanish translation in case you want to add it to the jar.

> lbl.button.ok=Aceptar
lbl.button.cancel=Cancelar
lbl.button.apply=&Aplicar
lbl.button.browse=&Buscar...
lbl.button.change=&Cambiar...
lbl.button.confirm=&Confirmar
lbl.button.close=&Cerrar
lbl.button.details.show=&Detalles >>
lbl.button.details.hide=<< &Detalles
lbl.preferences.title=Configuración
lbl.preferences.button.defaults=Restaurar &Defecto
lbl.preferences.button.defaults.tooltip=Restaurar valores por defecto para esta página
lbl.preferences.list.button.add=Nue&vo...
lbl.preferences.list.button.edit=E&ditar...
lbl.preferences.list.button.remove=&Eliminar
lbl.preferences.list.button.up=&Arriba
lbl.preferences.list.button.down=Aba&jo
lbl.preferences.default.value=Defecto: {0}
lbl.preferences.default.value.true=Habilitado
lbl.preferences.default.value.false=Deshabilitado
err.preferences.directory=El valor debe contener un directorio existente
err.preferences.file.existing=El valor debe contener un fichero existente
err.preferences.file.absolute.path=El valor debe contener una ruta existente
err.preferences.string=El campo contiene un valor inválido
err.preferences.date=El valor debe ser una fecha con el formato {0}
err.preferences.date.from=El valor debe ser una fecha mas grande o igual a {0}
err.preferences.date.to=El valor debe ser una fecha inferior o igual a {0}
err.preferences.date.range=El valor debe ser una fecha entre {0} y {1}
err.preferences.integer=El valor deb ser un número entero
err.preferences.integer.min=El valor debe ser un número entero mas grande o igual a {0}
err.preferences.integer.max=El valor debe ser un número entero menor o igual a {0}
err.preferences.integer.range=El valor debe ser un número entero entre {0} y {1}
err.preferences.decimal=El valor debe ser un número decimal
err.preferences.decimal.min=El valor debe ser un número decimal más grande o igual a {0}
err.preferences.decimal.max=El valor debe ser un número decimal menor o igual a {0}
err.preferences.decimal.range=El valor debe ser un número decimal entre {0} y {1}
err.preferences.combo.empty=El campo contiene un valor inválido
err.preferences.reload=Imposible recargar el fichero de configuración.
err.preferences.save=Imposible grabar el fichero de configuración.
lbl.preferences.email.dialog.add.title=Añadir dirección de email
lbl.preferences.email.dialog.edit.title=Editar dirección de email
lbl.preferences.email.dialog.message=Introduzca una dirección de email válida.
lbl.preferences.email.dialog.address=Dirección de email
lbl.preferences.uri.dialog.add.title=Añadir URI
lbl.preferences.uri.dialog.edit.title=Editar URI
lbl.preferences.uri.dialog.message=Introduzca una URI válida (esquema://host:port).
lbl.preferences.uri.dialog.address=URI
lbl.preferences.header.restart=* Debe reiniciar la aplicación para que los cambios surtan efecto.
lbl.preferences.logging.overridden=Esta configuración se ha sobreescrito externamente.
lbl.menu.item.file=&Fichero
lbl.menu.item.open=&Abrir
lbl.menu.item.copy=&Copiar
lbl.menu.item.select.all=Seleccionar &todo
lbl.menu.item.clear=Li&mpiar
lbl.menu.item.close=&Cerrar
lbl.menu.item.export=&Exportar...
lbl.error.dialog.reason={0}\n\nMotivo:\n{1}
lbl.system.info.dialog.title=Información del sistema
lbl.system.info.tab.properties=&Propiedades del sistema
lbl.system.info.tab.env=&Variables de entorno
lbl.system.info.tab.jvmArgs=&Argumentos de la máquina virtual de Java
lbl.system.info.table.key=Clave
lbl.system.info.table.value=Valor
lbl.system.info.detail.dialog.title=Detalles
lbl.system.info.notAvailable=Información del sistema no disponible.
lbl.system.info.export.title=Informe sobre la información del sistema generado el {0}
lbl.system.info.export.properties=[Propiedades del sistema]
lbl.system.info.export.env=[Variables de entorno]
lbl.system.info.export.jvmArgs=[Argumentos de la máquina virtual de Java]
err.system.info.export=Imposible exportar la información del sistema.
err.configuration.invalid=Propiedad \u0022{0}\u0022 inválida.
err.configuration.invalid.number=Propiedad \u0022{0}\u0022 inválida; el valor debe ser un número entre {1} y {2}.
err.configuration.invalid.char=Propiedad \u0022{0}\u0022 inválida; el valor debe ser un único carácter.
err.configuration.review=Revise el fichero {0}.
err.configuration.using.default=Usando el valor por defecto: {0}.
err.console.streams.redirect=Imposible redirigir System.out y System.err a la consola.
err.console.streams.reset=Imposible resetear System.out y System.err a sus valores por defecto.
err.console.capacity=No se puede determinar la máxima capacidad de la consola.
err.map.retrieve=No se puede obtener las coordenadas (map) ni los límites.
err.map.open=No se puede abrir el mapa.
err.delete.temp=No se puede borrar el fichero temporal \u0022{0}\u0022.
err.date.parse=No se puede parsear la fecha.
err.load.file=No se puede cargar el fichero \u0022{0}\u0022.
err.cocoa.enhancer.platform=La plataforma Cocoa no se ha detectado!
err.logging.housekeeping.datePattern=El patrón para la fecha que se ha dado \u0022{0}\u0022 no es un patrón válido. Se usará el patrón por defecto: \u0022{1}\u0022.
err.logging.housekeeping.maxHistory=El argumento ("maxHistory") debe ser más grande que cero. Se aplica el mínimo valor permitido ({0}).
msg.httpserver.bad.method=Método no permitido
msg.httpserver.request.headers=Requiriendo cabeceras: {0}
msg.httpserver.log.request={0} Requiriendo: {1} {2} {3} {4} {5}
msg.httpserver.log.response={0} Respuesta: {1} {2} {3} {4} {5} [{6}{7}]
msg.httpserver.resources.found=Encontrados {0} recursos estáticos.
msg.httpserver.started={0} Servidor en marcha y escuchando en el puerto {1}.
err.httpserver.traversal=Ataque potencial directorio transversal: \u0022{0}\u0022; dirección remota: {1}.
err.httpserver.start=No se puede arrancar el servidor HTTP.
err.httpserver.start.port=No se puede arrancar el servidor HTTP. Por vaor, compruebe si el puerto {0} ya está en uso.
err.httpserver.start.keystore.file=No se puede arrancar el servidor HTTP. Fichero ("Keystore") no encontrado.
err.httpserver.configuration.username=Error de configuración HTTP: el nombre de usuario no puede estar vacío.
err.httpserver.configuration.password=Error de configuración HTTP: la contraseña no puede estar vacía.
msg.httpserver.configuration.handlers.none=No se ha configurado ningun manejador (handler).
err.httpserver.authentication=Se ha registrado un intento de login sin las credenciales válidas: \u0022{0}\u0022 / \u0022{1}\u0022; dirección remota: {2}.
lbl.mqtt.qos.0=QoS 0 - Como mucho entragado una vez
lbl.mqtt.qos.1=QoS 1 - Al menos entregado una vez
lbl.mqtt.qos.2=QoS 2 - Entregado exactamente una vez

**Comment by albertus82** [comment]
Thank you a lot @vicenrico; if you want, you can create a **Pull request** by committing this **`jfacemessages_es.properties`** by yourself; I'll be glad to merge it and you will be automatically mentioned as a project contributor. If you can't do this, I'll commit the file by myself.

**Comment by vicenrico** [comment]
OK. I did. You'd better check it out because I don't know if everything went well.

**Comment by albertus82** [comment]
Yes, of course your request will be reviewed. Best regards.

**Comment by Albertus82** [comment]
@vicenrico, I saw your commit and it seems to be ok. You can create a _Pull request_ (you can follow [this procedure](https://help.github.com/articles/creating-a-pull-request-from-a-fork)), _allowing edits from maintainers_. Thank you again.
