### ISSUE TITLE
Error with long texts

### ISSUE THREAD

**Issue by vicenrico** [albertus82/jface-utils#3]
An error I've found.

`FILE(new PreferenceDetailsBuilder(MyPageDefinition.VARIOUS).name("file").label("File").build(), new FieldEditorDetailsBuilder(EnhancedFileFieldEditor.class).fileExtensions(new String[] { "*.txt;*.TXT" }).build()),`

When I put this preference field , I use for my db file path. When this path is very long, the preferences dialog grows to show the entire path, but I think it's the text widget who has to resize itself, and if the text inside is very long, no problem. The widget could show the tooltip with the entire path. I say so because my path is 140 chars long, and the preferences dialogs grows till 1200x600 px. In my program, are the widgets who resize themselves and keep the dialog with the fixed size (or minimum sizes) by default.

**Comment by albertus82** [comment]
Hi @vicenrico; I know that issue; I tried to fix it some time ago, but I eventually gave up after some tries. I'll keep this issue opened until I'll have solved this problem. Thank you.

**Comment by vicenrico** [comment]
Hello. I have a fix for this problem. In many of your controls you have the **grabExcessHorizontalSpace=true** line. You must provide a heightHint in order the main dialog not to grow. Sorryl, but I don't know how to pull this code. I've modified "doFillIntoGrid" in Enhancedlisteditor and it works!!!. If you don't know well SWT library, don't hesitate to ask, please

``` java
gd.heightHint=300;
//gd.grabExcessHorizontalSpace = true;
```

**Comment by vicenrico** [comment]
And there is, of course, widthhint

**Comment by albertus82** [comment]
Thank you @vicenrico, I hope I'll have time to implement the fix in the next weeks.

**Comment by albertus82** [comment]
Fixed in [v17.1.1](https://github.com/albertus82/jface-utils/releases/tag/v17.1.1).
